version: '3.9'
services:
  db:
    image: mongo:latest
    container_name: db
    expose:
      - "${MONGO_INITDB_PORT}"
    restart: always
    env_file:
      - .env
    ports:
      - "${MONGO_INITDB_PORT}:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: